In [19]:
#https://towardsdatascience.com/data-preprocessing-in-python-b52b652e37d5
#https://www.analyticsvidhya.com/blog/2022/07/step-by-step-exploratory-data-analysis-eda-using-python/
#https://medium.com/@yogeshojha/data-preprocessing-75485c7188c4
#https://www.geeksforgeeks.org/how-to-prepare-data-before-deploying-a-machine-learning-model/
#https://medium.com/@panData/eda-pipeline-techniques-and-methods-for-effective-machine-learning-models-506d8ff0d664  nice 
import numpy as np # used for handling numbers
import pandas as pd # used for handling the dataset
from sklearn.impute import SimpleImputer # used for handling missing data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder # used for encoding categorical data
from sklearn.model_selection import train_test_split # used for splitting training and testing data
from sklearn.preprocessing import StandardScaler # used for feature scaling

In [20]:
dataset = pd.read_csv('Data.csv') # to import the dataset into a variable
# Splitting the attributes into independent and dependent attributes
X = dataset.iloc[:, :-1].values # attributes to determine dependent variable / Class
Y = dataset.iloc[:, -1].values # dependent variable / Class

In [21]:
dataset

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes

In [24]:
X

array([['India', 49.0, 86400.0],
       ['Brazil', 32.0, 57600.0],
       ['USA', 35.0, 64800.0],
       ['Brazil', 43.0, 73200.0],
       ['USA', 45.0, nan],
       ['India', 40.0, 69600.0],
       ['Brazil', nan, 62400.0],
       ['India', 53.0, 94800.0],
       ['USA', 55.0, 99600.0],
       ['India', 42.0, 80400.0]], dtype=object)

In [35]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [38]:
dataset.iloc[:,1:-1]

Age   Income
0  49.0  86400.0
1  32.0  57600.0
2  35.0  64800.0
3  43.0  73200.0
4  45.0      NaN
5  40.0  69600.0
6   NaN  62400.0
7  53.0  94800.0
8  55.0  99600.0
9  42.0  80400.0

In [36]:
# handling the missing data and replace missing values with nan from numpy and replace with mean of all the other values
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') 
imputer = imputer.fit(X[:, 1:])
X[:, 1:] = imputer.transform(X[:, 1:])

In [37]:
X[:, 1:]

array([[49.0, 86400.0],
       [32.0, 57600.0],
       [35.0, 64800.0],
       [43.0, 73200.0],
       [45.0, 76533.33333333333],
       [40.0, 69600.0],
       [43.77777777777778, 62400.0],
       [53.0, 94800.0],
       [55.0, 99600.0],
       [42.0, 80400.0]], dtype=object)

In [ ]:
#The most common way is to keep 80% of the dataset as the training set, and the rest 20% of the dataset as the test set.

In [9]:
X_train

array([['USA', 45.0, nan],
       ['India', 42.0, 80400.0],
       ['Brazil', 32.0, 57600.0],
       ['Brazil', nan, 62400.0],
       ['India', 53.0, 94800.0],
       ['Brazil', 43.0, 73200.0],
       ['India', 49.0, 86400.0],
       ['India', 40.0, 69600.0]], dtype=object)

In [ ]:
#  selecting matrix and vector elements 
#https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html

In [39]:
# handling the missing data and replace missing values with nan from numpy and replace with mean of all the other values
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') 
imputer = imputer.fit(X[:, 1:])
X[:, 1:] = imputer.transform(X[:, 1:])#  select all rows and everything (columns) after the first column#  https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html

In [13]:
X[:, 0]

array([0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0], dtype=object)

In [40]:
# encode categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [0])],   remainder='passthrough')
#onehotencoder = OneHotEncoder(categorical_features=[0])
X = np.array(columnTransformer.fit_transform(X))
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)


In [41]:
X

array([[0.0, 1.0, 0.0, 49.0, 86400.0],
       [1.0, 0.0, 0.0, 32.0, 57600.0],
       [0.0, 0.0, 1.0, 35.0, 64800.0],
       [1.0, 0.0, 0.0, 43.0, 73200.0],
       [0.0, 0.0, 1.0, 45.0, 76533.33333333333],
       [0.0, 1.0, 0.0, 40.0, 69600.0],
       [1.0, 0.0, 0.0, 43.77777777777778, 62400.0],
       [0.0, 1.0, 0.0, 53.0, 94800.0],
       [0.0, 0.0, 1.0, 55.0, 99600.0],
       [0.0, 1.0, 0.0, 42.0, 80400.0]], dtype=object)

In [15]:
Y  ###  array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [42]:
# splitting the dataset into training set and test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [43]:
# splitting the dataset into training set and test set
X_train

array([[0.0, 0.0, 1.0, 45.0, 76533.33333333333],
       [0.0, 1.0, 0.0, 42.0, 80400.0],
       [1.0, 0.0, 0.0, 32.0, 57600.0],
       [1.0, 0.0, 0.0, 43.77777777777778, 62400.0],
       [0.0, 1.0, 0.0, 53.0, 94800.0],
       [1.0, 0.0, 0.0, 43.0, 73200.0],
       [0.0, 1.0, 0.0, 49.0, 86400.0],
       [0.0, 1.0, 0.0, 40.0, 69600.0]], dtype=object)

In [30]:
# X_test

array([[1.0, 0.0, 0.0, 1.0, 35.0, 64800.0],
       [1.0, 0.0, 0.0, 1.0, 55.0, 99600.0]], dtype=object)

In [31]:
# Y_train

array([1, 1, 1, 0, 1, 0, 0, 1], dtype=int64)

In [32]:
#Y_test

array([0, 0], dtype=int64)

In [33]:
# feature scaling

sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


In [34]:
X_train

array([[ 0.77459667, -0.77459667, -1.        ,  2.64575131,  0.26306757,
         0.12381479],
       [ 0.77459667, -0.77459667,  1.        , -0.37796447, -0.25350148,
         0.46175632],
       [-1.29099445,  1.29099445, -1.        , -0.37796447, -1.97539832,
        -1.53093341],
       [-1.29099445,  1.29099445, -1.        , -0.37796447,  0.05261351,
        -1.11141978],
       [ 0.77459667, -0.77459667,  1.        , -0.37796447,  1.64058505,
         1.7202972 ],
       [-1.29099445,  1.29099445, -1.        , -0.37796447, -0.0813118 ,
        -0.16751412],
       [ 0.77459667, -0.77459667,  1.        , -0.37796447,  0.95182631,
         0.98614835],
       [ 0.77459667, -0.77459667,  1.        , -0.37796447, -0.59788085,
        -0.48214934]])

In [35]:
X_test

array([[ 0.77459667, -0.77459667, -1.        ,  2.64575131, -1.45882927,
        -0.90166297],
       [ 0.77459667, -0.77459667, -1.        ,  2.64575131,  1.98496442,
         2.13981082]])